### ISSUE TITLE
BindingFragment - ToolbarFragment

### ISSUE THREAD

**Issue by nemislimus** [nemislimus/practicum-android-diploma#17]

**Comment by amdoit-git** [comment]
Эту ветку предлагаю сделать в несколько человек. У каждого же есть наработанные фишки, которые мы хотим добавить в проект. Унаследуем ее от develop. Потом унаследуемся от нее.  Вкинем в нее все фишки. Смержим их в эту ветку. А потом уже смержим ее в develop

**Comment by Yarogi** [comment]
Под такие нужды можно просто отдельное Issue сделать, каждый просто под свое. Я сюда сейчас добавлю следующие:
- [] BindingFragment
- [] ToolbarFragment

**Comment by Yarogi** [comment]
Перемименовал, чтоб путаицы не было
